### ISSUE TITLE
[Bug]: No default iconify icon set found.

### ISSUE THREAD

**Issue by bishwajitcadhikary** [webdevnerdstuff/vuetify-inline-fields#56]
### Bug description

How do i set custom iconify icon set?

I'm using tabler icon

### Steps to reproduce

![CleanShot 2024-10-04 at 10  04 17@2x](https://github.com/user-attachments/assets/8174752b-2da3-4c18-92e5-3bee95456483)

### Reproduction link

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
Without setting it up to test, I'm going to guess that this is more of a feature addition than a bug. I'll see what I can do. In the meantime if you have a working example I can use that will speed up this process. Please try to provide a reproduction link.

**Comment by webdevnerdstuff** [comment]
Closing the issue due to inactivity
